[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
claynosaurz_staking = "9qhxfZcUgj5Et8JGK5TZ62Zdtrqf94ojknWmQdEiyFpv"

[programs.devnet]
claynosaurz_staking = "9qhxfZcUgj5Et8JGK5TZ62Zdtrqf94ojknWmQdEiyFpv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
